apiVersion: v1
kind: Secret
metadata:
  name: games-secret
  namespace: fcg-games
  labels:
    app: games
type: Opaque
stringData:
  GAMES_DB_CONNECTION_STRING: $(GAMES_DB_CONNECTION_STRING)
  RABBITMQ_CONNECTION_STRING: $(RABBITMQ_CONNECTION_STRING)
  OPENSEARCH_USER: $(OPENSEARCH_USER)
  OPENSEARCH_PASSWORD: $(OPENSEARCH_PASSWORD)
  JWT_ISSUER: $(JWT_ISSUER)
  JWT_AUDIENCE: $(JWT_AUDIENCE)
  JWT_KEY: $(JWT_KEY)